In [1]:
import numpy as np
import psutil

In [2]:
# Function to print memory usage
def print_memory_usage():
    process = psutil.Process()
    mem_info = process.memory_info()
    print(f"Memory Usage: {mem_info.rss / (1024 ** 2):.2f} MB")


In [ ]:
# Multiply two large matrices
# FAILED if matrices too large and memory is not enough

# A = np.random.rand(100000, 50)
# B = np.random.rand(50, 100000)

# # Standard multiplication
# C = np.dot(A, B)  # Or A @ B

# # Print the shape of the result
# print("Shape of C:", C.shape)

# # Optionally, print a small part of the matrix
# print("First 5x5 block of C:\n", C[:5, :5])

In [ ]:
# Use numpy.memmap for Disk-Based Computation
# PERFECT METHOD FOR LOW MEMORY SYSTEMS
import numpy as np

print("Memory usage before multiplication:")
print_memory_usage()

A = np.memmap('A.dat', dtype='float32', mode='w+', shape=(100000, 1))
B = np.memmap('B.dat', dtype='float32', mode='w+', shape=(1, 100000))
C = np.memmap('C.dat', dtype='float32', mode='w+', shape=(100000, 100000))

# Fill A and B with random values (example)
A[:] = np.random.rand(100000, 1)
B[:] = np.random.rand(1, 100000)

# Multiply in chunks
for i in range(A.shape[0]):
    C[i, :] = A[i, :] @ B  # Process row-by-row

# Check memory usage after multiplication
print("Memory usage after multiplication:")
print_memory_usage()

# # Print the shape of the result
print("Shape of C:", C.shape)

# # Optionally, print a small part of the matrix
print("First 5x5 block of C:\n", C[:5, :5])

Memory usage (init):
Memory Usage: 99.39 MB
Memory usage before multiplication:
Memory Usage: 99.41 MB
Memory usage after multiplication:
Memory Usage: 3471.30 MB
Shape of C: (100000, 100000)
First 5x5 block of C:
 [[0.20294341 0.31546688 0.68615556 0.152865   0.65581053]
 [0.04588334 0.07132371 0.15513247 0.03456115 0.14827177]
 [0.08352435 0.12983505 0.28239745 0.06291384 0.2699085 ]
 [0.01826654 0.02839456 0.06175954 0.01375908 0.05902824]
 [0.07345313 0.11417976 0.24834643 0.0553278  0.23736338]]


In [4]:
print("Memory usage after multiplication:")
print_memory_usage()

Memory usage after multiplication:
Memory Usage: 1887.77 MB


In [3]:
# Matrix Multiplication with MPS

import torch

# Move tensors to GPU (MPS)
device = torch.device("mps")  # Use "cpu" if no GPU is available

A = torch.rand(100000, 50, device=device)
B = torch.rand(50, 100000, device=device)

C = torch.matmul(A, B)  # GPU-accelerated matrix multiplication


RuntimeError: Invalid buffer size: 37.25 GB

In [2]:
!pip install cupy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 7.7 MB/s eta 0:00:00a 0:00:01
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      Generating cache key from header files...
      Cache key (1610 files matching /private/var/folders/yr/qjfqfcxs79b91s4n4v1zp0b80000gn/T/pip-install-0wnzsiin/cupy_0de7c0e6b02d427da42326562bb7297e/cupy/_core/include/**): 5a9d2f850421ee67b5b715210ae3691771282212
      Error: macOS is no longer supported
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


In [ ]:
# Use GPU Acceleration (cupy or torch.cuda)
# If you have a GPU, cupy or torch.cuda can handle large matrices efficiently.
# CANNOT BE USED IN MACOSX

import cupy as cp

A = cp.random.rand(100000, 50)
B = cp.random.rand(50, 100000)

C = A @ B  # Performed on GPU


ModuleNotFoundError: No module named 'cupy'

In [4]:
# Use scipy.sparse for Sparse Matrices
# If your matrices contain many zeros, use scipy.sparse:

import numpy as np
from scipy.sparse import csr_matrix

A = csr_matrix(np.random.rand(100000, 50))
B = csr_matrix(np.random.rand(50, 100000))

C = A @ B  # Sparse multiplication, saving memory


: 

In [2]:
!pip install dask

  Using cached cloudpickle-3.1.1-py3-none-any.whl.metadata (7.1 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 14.2 MB/s eta 0:00:00a 0:00:01
Using cached cloudpickle-3.1.1-py3-none-any.whl (20 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.4/56.4 kB 6.2 MB/s eta 0:00:00


In [ ]:
# Use dask for Out-of-Core Computation
# dask.array allows parallel and chunk-based computations.

import dask.array as da

A = da.random.random((100000, 50), chunks=(1000, 50))
B = da.random.random((50, 100000), chunks=(50, 1000))

C = A @ B  # Computation is lazy, not in memory yet
C.compute()  # Compute when needed


/opt/anaconda3/envs/Python_3-9-19/lib/python3.9/site-packages/dask/array/routines.py:450: PerformanceWarning: Increasing number of chunks by factor of 100
  out = blockwise(


: 

In [1]:
!pip install jax

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 21.5 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.7/66.7 MB 33.4 MB/s eta 0:00:0000:0100:01


In [7]:
import jax.numpy as jnp

A = jnp.ones((100000, 10))
B = jnp.ones((10, 100000))

C = jnp.dot(A, B)  # Automatically optimized

# # Print the shape of the result
print("Shape of C:", C.shape)

# # Optionally, print a small part of the matrix
print("First 5x5 block of C:\n", C[:5, :5])

: 

In [2]:
import tensorflow as tf

A = tf.random.normal([100000, 10])
B = tf.random.normal([10, 100000])

C = tf.linalg.matmul(A, B)  # GPU-accelerated

# # Print the shape of the result
print("Shape of C:", C.shape)

# # Optionally, print a small part of the matrix
print("First 5x5 block of C:\n", C[:5, :5])

: 

In [ ]:
import pyopencl as cl
import numpy as np

ctx = cl.create_some_context()
queue = cl.CommandQueue(ctx)

A = np.random.rand(10000, 5000).astype(np.float32)
B = np.random.rand(5000, 8000).astype(np.float32)

# Transfer data to the GPU
A_buf = cl.Buffer(ctx, cl.mem_flags.READ_ONLY | cl.mem_flags.COPY_HOST_PTR, hostbuf=A)
B_buf = cl.Buffer(ctx, cl.mem_flags.READ_ONLY | cl.mem_flags.COPY_HOST_PTR, hostbuf=B)
C_buf = cl.Buffer(ctx, cl.mem_flags.WRITE_ONLY, A.nbytes * B.shape[1])

# OpenCL kernel for matrix multiplication (requires setup)
# You'd need to write a kernel function to compute the matrix product.

